src/Entity/Task.php
<?php

namespace App\Entity;

use App\Repository\TaskRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: TaskRepository::class)]
class Task
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 255)]
    private ?string $title = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column]
    private ?bool $is_done = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $created_at = null;

    #[ORM\ManyToOne(inversedBy: 'tasks')]
    #[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
    private ?User $user = null;

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): static
    {
        $this->title = $title;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): static
    {
        $this->content = $content;

        return $this;
    }

    public function isIsDone(): ?bool
    {
        return $this->is_done;
    }

    public function setIsDone(bool $is_done): static
    {
        $this->is_done = $is_done;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): static
    {
        $this->created_at = $created_at;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }
}

src/Form/TaskType.php
<?php

namespace App\Form;

use App\Entity\Task;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\TextType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Validator\Constraints\Length;
use Symfony\Component\Validator\Constraints\NotBlank;

class TaskType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('title', TextType::class, [
                'label' => 'Titre',
                'constraints' => [
                    new NotBlank([
                        'message' => 'Veuillez saisir un titre pour votre tâche.'
                    ]),
                    new Length([
                        'min' => 3,
                        'minMessage' => 'Le titre doit contenir au moins {{ limit }} caractères.',
                        'max' => 255,
                        'maxMessage' => 'Le titre doit contenir au maximum {{ limit }} caractères.'
                    ])
                ],
                'required' => true,
            ])
            ->add('content', null, [
                'label' => 'Contenu',
                'constraints' => [
                    new NotBlank([
                        'message' => 'Veuillez saisir un contenu pour votre tâche.'
                    ]),
                    new Length([
                        'min' => 3,
                        'minMessage' => 'Le contenu doit contenir au moins {{ limit }} caractères.'
                    ])
                ],
                'required' => true,
            ])
            ->add('is_done', null, [
                'label' => 'Tâche terminée ?',
                'required' => false,
            ])
            //->add('created_at')
            //->add('user')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Task::class,
        ]);
    }
}

src/Controller/TaskController.php
<?php

namespace App\Controller;

use App\Entity\Task;
use App\Form\NewTaskType;
use App\Form\EditTaskType;
use App\Repository\TaskRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

#[Route('/taches', name: 'app_task_')]
class TaskController extends AbstractController
{
    #[Route('', name: 'index', methods: ['GET'])]
    public function index(TaskRepository $taskRepository): Response
    {
        if (!$this->getUser()) {
            return $this->redirectToRoute('app_home');
        }

        if ($this->isGranted('ROLE_ADMIN')) {
            return $this->render('task/index.html.twig', [
                'tasks' => $taskRepository->findBy(['user' => $this->getUser()], ['is_done' => 'ASC', 'created_at' => 'ASC']),
                'tasksAnonym' => $taskRepository->findBy(['user' => null], ['is_done' => 'ASC', 'created_at' => 'ASC'])
            ]);
        } else {
            return $this->render('task/index.html.twig', [
                'tasks' => $taskRepository->findBy(['user' => $this->getUser()], ['is_done' => 'ASC', 'created_at' => 'ASC'])
            ]);
        }
    }

    #[Route('/ajouter', name: 'new', methods: ['GET', 'POST'])]
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        if (!$this->getUser()) {
            return $this->redirectToRoute('app_home');
        }

        $task = new Task();
        $form = $this->createForm(NewTaskType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $task->setIsDone(false);
            $task->setCreatedAt(new \DateTimeImmutable());
            $task->setUser($this->getUser());
            
            $entityManager->persist($task);
            $entityManager->flush();

            $this->addFlash('successTaskAdd', 'La tâche '.$task->getTitle().' a été ajoutée avec succès.');

            return $this->redirectToRoute('app_task_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('task/new.html.twig', [
            'task' => $task,
            'form' => $form,
            'addTask' => true
        ]);
    }

    #[Route('/{id}/modifier', name: 'edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Task $task, EntityManagerInterface $entityManager): Response
    {
        if (!$this->getUser() || $this->getUser() !== $task->getUser() && !$this->isGranted('ROLE_ADMIN')) {
            return $this->redirectToRoute('app_home');
        }

        $form = $this->createForm(EditTaskType::class, $task);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            $this->addFlash('successTaskEdit', 'La tâche '.$task->getTitle().' a été modifiée avec succès.');

            return $this->redirectToRoute('app_task_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('task/edit.html.twig', [
            'task' => $task,
            'form' => $form,
            'editTask' => true
        ]);
    }

    #[Route('/{id}/supprimer', name: 'delete', methods: ['POST'])]
    public function delete(Task $task, EntityManagerInterface $entityManager): Response
    {
        if (!$this->getUser() || $this->getUser() !== $task->getUser() && !$this->isGranted('ROLE_ADMIN')) {
            return $this->redirectToRoute('app_home');
        }

        $entityManager->remove($task);
        $entityManager->flush();

        $this->addFlash('successTaskDelete', 'La tâche '.$task->getTitle().' a été supprimée avec succès.');

        return $this->redirectToRoute('app_task_index', [], Response::HTTP_SEE_OTHER);
    }
}

templates/task/_delete_form.html.twig
<form method="post" action="{{ path('app_task_delete', {'id': task.id}) }}" onsubmit="return confirm('Êtes-vous sûr de bien vouloir supprimer cette tâche ?');">
    <button class="badge text-bg-danger py-2 fs-6 border-0"><i class="fas fa-trash"></i></button>
</form>

templates/task/_form.html.twig
{{ form_start(form) }}
    <div class="form-group mb-3">
        {{ form_label(form.title, 'Titre', {'label_attr': {'class': 'form-label fs-3'}})}}
        {{ form_widget(form.title, {'attr': {'class': 'form-control w-75 text-center mx-auto'}})}}
    </div>

    <div class="form-group mb-3">
        {{ form_label(form.content, 'Contenu', {'label_attr': {'class': 'form-label fs-3'}})}}
        {{ form_widget(form.content, {'attr': {'class': 'form-control w-75 text-center mx-auto', 'rows': '5'}})}}
    </div>

    {% if editTask is defined %}
    <div class="form-group mb-4">
        {{ form_label(form.is_done, 'Terminé ?', {'label_attr': {'class': 'form-label fs-3'}})}}
        {{ form_widget(form.is_done, {'attr': {'class': 'form-check w-75 text-center mx-auto'}})}}
    </div>
    {% endif %}

    <button class="btn text-white border">{{ button_label|default('Ajouter') }}</button>
{{ form_end(form) }}

templates/task/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ task.title }} - modifier une tâche{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <h1 class="text-center mt-3 mb-3">Modifier une tâche</h1>

        <div class="col-12 col-md-6 offset-md-3">
            <div class="text-center border shadow rounded-4 p-4 mb-5">
                {{ include('task/_form.html.twig', {'button_label': 'Modifier'}) }}
            </div>
        </div>
    </div>
</div>
{% endblock %}

templates/task/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des tâches - ToDo & Co{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        {% for flash_message in app.flashes('successTaskAdd') %}
            <div class="alert alert-success" role="alert">
                {{ flash_message }}
            </div>
        {% endfor %}

        {% for flash_message in app.flashes('successTaskEdit') %}
            <div class="alert alert-success" role="alert">
                {{ flash_message }}
            </div>
        {% endfor %}

        {% for flash_message in app.flashes('successTaskDelete') %}
            <div class="alert alert-success" role="alert">
                {{ flash_message }}
            </div>
        {% endfor %}

        <h1 class="text-center mt-3 mb-3">Liste des tâches</h1>

        <a class="text-center mb-3" href="{{ path('app_task_new') }}"><span class="badge text-bg-success py-2 fs-6"><i class="fas fa-plus"></i> Créer une nouvelle tâche</span></a>

        <div class="col-12 mb-3">
            <div class="row g-3">
                {% for task in tasks %}
                <div class="col-12 col-md-6 col-lg-4">
                    {% if task.isDone %}
                    <div class="rounded-3 border border-secondary">
                    {% else %}
                    <div class="rounded-3 border border-info">
                    {% endif %}
                        <div class="d-flex justify-content-between align-items-center px-3 py-2">
                            <span>{{ task.title }}</span>
        
                            {% if app.user %}
                            <div class="d-flex justify-content-between">
                                <a href="{{ path('app_task_edit', {'id': task.id}) }}"><span class="badge text-bg-warning py-2 me-3 fs-6"><i class="fas fa-edit"></i></span></a>
        
                                {{ include('task/_delete_form.html.twig') }}
                            </div>
                            {% endif %}
                        </div>
                        <div class="px-3 py-2">
                            {{ task.content }}
                        </div>
                        <div class="d-flex justify-content-between align-items-center px-3 py-2">
                            <span class="badge text-bg-light py-2 fs-6 mb-0"><i class="fas fa-user"></i> {{ task.user }}</span>
        
                            {{ task.createdAt|date('d/m/Y') }}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>

        {% if tasksAnonym is defined and tasksAnonym is not empty %}
        <h2 class="text-center mt-3 mb-3">Liste des tâches anonymes</h1>

        <div class="col-12 mb-3">
            <div class="row g-3">
                {% for taskAnonym in tasksAnonym %}
                <div class="col-12 col-md-6 col-lg-4">
                    {% if taskAnonym.isDone %}
                    <div class="rounded-3 border border-secondary">
                    {% else %}
                    <div class="rounded-3 border border-info">
                    {% endif %}
                        <div class="d-flex justify-content-between align-items-center px-3 py-2">
                            <span>{{ taskAnonym.title }}</span>
        
                            <div class="d-flex justify-content-between">
                                <a href="{{ path('app_task_edit', {'id': taskAnonym.id}) }}"><span class="badge text-bg-warning py-2 me-3 fs-6"><i class="fas fa-edit"></i></span></a>
        
                                <form method="post" action="{{ path('app_task_delete', {'id': taskAnonym.id}) }}" onsubmit="return confirm('Êtes-vous sûr de bien vouloir supprimer cette tâche ?');">
                                    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ taskAnonym.id) }}">
                                    <button class="badge text-bg-danger py-2 fs-6 border-0"><i class="fas fa-trash"></i></button>
                                </form>
                            </div>
                        </div>
                        <div class="px-3 py-2">
                            {{ taskAnonym.content }}
                        </div>
                        <div class="d-flex justify-content-between align-items-center px-3 py-2">
                            <span class="badge text-bg-light py-2 fs-6 mb-1"><i class="fas fa-user"></i> Anonyme</span>
        
                            {{ taskAnonym.createdAt|date('d/m/Y') }}
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
        {% endif %}
    </div>
</div>
{% endblock %}

templates/task/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}Nouvelle tâche - ToDo & Co{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <h1 class="text-center mt-3 mb-3">Ajouter une nouvelle tâche</h1>

        <div class="col-12 col-md-6 offset-md-3">
            <div class="text-center border shadow rounded-4 p-4 mb-5">
                {{ include('task/_form.html.twig') }}
            </div>
        </div>
    </div>
</div>
{% endblock %}